import type { Badge, Challenge } from './types'

/**
 * Catalogue des défis.
 *
 * Chaque défi doit être vérifiable à partir des données que l'utilisateur
 * saisit lui-même, et formulé positivement : on célèbre une action réussie,
 * jamais une privation subie.
 */
export const CHALLENGES: Challenge[] = [
  // --- Quotidiens -----------------------------------------------------------
  {
    id: 'd_log',
    title: 'Pointer le jour',
    description: "Ouvrir Budgette et noter les dépenses du jour. Trente secondes qui changent tout.",
    cadence: 'daily',
    difficulty: 'douce',
    xp: 10,
    icon: 'PenLine',
    tone: 'mint',
    target: 1,
    unit: 'saisie',
  },
  {
    id: 'd_no_spend',
    title: 'Journée sans dépense',
    description: "Traverser la journée sans sortir un euro. Le réflexe le plus rentable qui existe.",
    cadence: 'daily',
    difficulty: 'moyenne',
    xp: 25,
    icon: 'Moon',
    tone: 'orchid',
    target: 1,
    unit: 'journée',
    suitedTo: ['emergency', 'debt_exit', 'freedom'],
  },
  {
    id: 'd_home_meal',
    title: 'Cuisine maison',
    description: 'Aucune livraison de repas aujourd’hui. Votre cuisine vous remercie, votre solde aussi.',
    cadence: 'daily',
    difficulty: 'douce',
    xp: 20,
    icon: 'ChefHat',
    tone: 'mint',
    target: 1,
    unit: 'journée',
  },
  {
    id: 'd_no_cash',
    title: 'Zéro retrait',
    description: "Pas de passage au distributeur. Les retraits hors réseau coûtent souvent une commission.",
    cadence: 'daily',
    difficulty: 'douce',
    xp: 15,
    icon: 'Banknote',
    tone: 'berry',
    target: 1,
    unit: 'journée',
    suitedTo: ['debt_exit'],
  },
  {
    id: 'd_round_up',
    title: "L'arrondi du soir",
    description: 'Mettre de côté les centimes de la journée. Indolore, et ça finit par compter.',
    cadence: 'daily',
    difficulty: 'douce',
    xp: 15,
    icon: 'CircleDollarSign',
    tone: 'amber',
    target: 1,
    unit: 'arrondi',
  },
  {
    id: 'd_cart_pause',
    title: 'La pause de 24 heures',
    description: "Repousser d'un jour tout achat non essentiel de plus de 50 €. Souvent, l'envie passe.",
    cadence: 'daily',
    difficulty: 'moyenne',
    xp: 30,
    icon: 'Hourglass',
    tone: 'indigo',
    target: 1,
    unit: 'report',
    suitedTo: ['purchase'],
  },

  // --- Hebdomadaires --------------------------------------------------------
  {
    id: 'w_no_delivery',
    title: 'Semaine sans livraison',
    description: 'Sept jours sans commander de repas. Le poste le plus élastique de la plupart des budgets.',
    cadence: 'weekly',
    difficulty: 'costaude',
    xp: 120,
    icon: 'Bike',
    tone: 'orchid',
    target: 7,
    unit: 'jours',
    suitedTo: ['emergency', 'travel', 'debt_exit'],
  },
  {
    id: 'w_three_no_spend',
    title: 'Trois jours blancs',
    description: 'Trois journées sans dépense dans la même semaine.',
    cadence: 'weekly',
    difficulty: 'moyenne',
    xp: 130,
    icon: 'CalendarCheck',
    tone: 'mint',
    target: 3,
    unit: 'journées',
  },
  {
    id: 'w_grocery_budget',
    title: 'Courses maîtrisées',
    description: "Tenir l'enveloppe courses de la semaine, liste en main.",
    cadence: 'weekly',
    difficulty: 'moyenne',
    xp: 100,
    icon: 'ShoppingBasket',
    tone: 'indigo',
    target: 1,
    unit: 'semaine',
  },
  {
    id: 'w_review',
    title: 'Le point du dimanche',
    description: 'Cinq minutes pour relire la semaine et ajuster la suivante.',
    cadence: 'weekly',
    difficulty: 'douce',
    xp: 60,
    icon: 'Telescope',
    tone: 'mint',
    target: 1,
    unit: 'bilan',
  },
  {
    id: 'w_cash_only',
    title: 'Semaine en espèces',
    description: "Retirer l'enveloppe de la semaine et ne dépenser que ça. On voit l'argent partir, on freine tout seul.",
    cadence: 'weekly',
    difficulty: 'costaude',
    xp: 110,
    icon: 'Wallet',
    tone: 'amber',
    target: 1,
    unit: 'semaine',
    suitedTo: ['debt_exit'],
  },
  {
    id: 'w_sell',
    title: 'Un objet, une vie nouvelle',
    description: "Revendre un objet qui dort. L'argent va directement sur une poche d'épargne.",
    cadence: 'weekly',
    difficulty: 'moyenne',
    xp: 90,
    icon: 'PackageOpen',
    tone: 'amber',
    target: 1,
    unit: 'vente',
    suitedTo: ['purchase', 'travel'],
  },

  // --- Mensuels -------------------------------------------------------------
  {
    id: 'm_close',
    title: 'Clôturer le mois',
    description: 'Saisir le mois complet et le figer. Le rituel qui fait tenir tout le reste.',
    cadence: 'monthly',
    difficulty: 'douce',
    xp: 150,
    icon: 'BookCheck',
    tone: 'mint',
    target: 1,
    unit: 'clôture',
  },
  {
    id: 'm_no_atm',
    title: 'Mois sans distributeur',
    description: 'Aucun retrait d’espèces du mois. Zéro commission de retrait déplacé.',
    cadence: 'monthly',
    difficulty: 'costaude',
    xp: 200,
    icon: 'Landmark',
    tone: 'berry',
    target: 1,
    unit: 'mois',
    suitedTo: ['debt_exit', 'emergency'],
  },
  {
    id: 'm_save_10',
    title: 'Le dixième sacré',
    description: "Épargner au moins 10 % du revenu du mois, avant toute dépense plaisir.",
    cadence: 'monthly',
    difficulty: 'moyenne',
    xp: 250,
    icon: 'PiggyBank',
    tone: 'amber',
    target: 10,
    unit: '% du revenu',
  },
  {
    id: 'm_sub_audit',
    title: 'Chasse aux abonnements',
    description: 'Passer en revue tous les prélèvements récurrents et résilier au moins un.',
    cadence: 'monthly',
    difficulty: 'moyenne',
    xp: 180,
    icon: 'Scissors',
    tone: 'orchid',
    target: 1,
    unit: 'résiliation',
    suitedTo: ['freedom', 'travel'],
  },
  {
    id: 'm_under_budget',
    title: 'Enveloppe tenue',
    description: 'Rester sous le plafond de dépenses plaisir fixé en début de mois.',
    cadence: 'monthly',
    difficulty: 'costaude',
    xp: 220,
    icon: 'Target',
    tone: 'indigo',
    target: 1,
    unit: 'mois',
  },
  {
    id: 'm_no_overdraft',
    title: 'Jamais dans le rouge',
    description: 'Terminer le mois sans un seul jour de découvert.',
    cadence: 'monthly',
    difficulty: 'costaude',
    xp: 240,
    icon: 'ShieldCheck',
    tone: 'mint',
    target: 1,
    unit: 'mois',
    suitedTo: ['debt_exit'],
  },
  {
    id: 'm_extra_debt',
    title: 'Coup de rabot',
    description: 'Faire un remboursement anticipé, même modeste, sur une dette en cours.',
    cadence: 'monthly',
    difficulty: 'héroïque',
    xp: 260,
    icon: 'Hammer',
    tone: 'berry',
    target: 1,
    unit: 'remboursement',
    suitedTo: ['debt_exit'],
  },

  // --- Annuels --------------------------------------------------------------
  {
    id: 'y_12_closed',
    title: 'Douze mois au compteur',
    description: "Clôturer douze mois d'affilée. Une année entière de visibilité.",
    cadence: 'yearly',
    difficulty: 'costaude',
    xp: 1000,
    icon: 'CalendarRange',
    tone: 'mint',
    target: 12,
    unit: 'mois',
  },
  {
    id: 'y_emergency_1m',
    title: 'Premier mois de sécurité',
    description: "Constituer l'équivalent d'un mois de charges en fonds d'urgence.",
    cadence: 'yearly',
    difficulty: 'costaude',
    xp: 800,
    icon: 'Umbrella',
    tone: 'amber',
    target: 1,
    unit: 'mois de charges',
    suitedTo: ['emergency'],
  },
  {
    id: 'y_save_15',
    title: "L'année du quinzième",
    description: "Tenir un taux d'épargne annuel d'au moins 15 %.",
    cadence: 'yearly',
    difficulty: 'héroïque',
    xp: 1200,
    icon: 'TrendingUp',
    tone: 'amber',
    target: 15,
    unit: '% annuels',
    suitedTo: ['retirement', 'freedom', 'home'],
  },
  {
    id: 'y_debt_free',
    title: 'Année en terrain sec',
    description: 'Douze mois sans le moindre découvert.',
    cadence: 'yearly',
    difficulty: 'héroïque',
    xp: 900,
    icon: 'Sun',
    tone: 'indigo',
    target: 12,
    unit: 'mois',
    suitedTo: ['debt_exit'],
  },
  {
    id: 'y_goal',
    title: 'Objectif atteint',
    description: 'Mener un objectif financier jusqu’à son terme dans l’année.',
    cadence: 'yearly',
    difficulty: 'héroïque',
    xp: 1000,
    icon: 'Flag',
    tone: 'orchid',
    target: 1,
    unit: 'objectif',
  },
]

export const CHALLENGE_BY_ID: Record<string, Challenge> = Object.fromEntries(
  CHALLENGES.map((c) => [c.id, c]),
)

/** Catalogue des badges. Le critère reste visible tant que le badge est verrouillé. */
export const BADGES: Badge[] = [
  {
    id: 'first_step',
    label: 'Premier pas',
    description: 'Vous avez saisi votre premier mois. Tout commence là.',
    criteria: 'Saisir un premier mois',
    rarity: 'commun',
    icon: 'Footprints',
    tone: 'mint',
    xp: 50,
  },
  {
    id: 'streak_7',
    label: 'Sept jours',
    description: 'Une semaine de suivi sans interruption.',
    criteria: '7 jours de série',
    rarity: 'commun',
    icon: 'Flame',
    tone: 'berry',
    xp: 80,
  },
  {
    id: 'streak_30',
    label: 'Le mois entier',
    description: 'Trente jours de suivi consécutifs. L’habitude est prise.',
    criteria: '30 jours de série',
    rarity: 'rare',
    icon: 'Flame',
    tone: 'berry',
    xp: 250,
  },
  {
    id: 'streak_100',
    label: 'Cent jours',
    description: 'Cent jours d’affilée. Peu de gens vont jusque-là.',
    criteria: '100 jours de série',
    rarity: 'épique',
    icon: 'Flame',
    tone: 'amber',
    xp: 700,
  },
  {
    id: 'streak_365',
    label: 'Une année pleine',
    description: 'Trois cent soixante-cinq jours. Vous ne subissez plus votre budget.',
    criteria: '365 jours de série',
    rarity: 'légendaire',
    icon: 'Crown',
    tone: 'amber',
    xp: 2500,
  },
  {
    id: 'green_month',
    label: 'Mois dans le vert',
    description: 'Un mois clôturé avec un solde positif.',
    criteria: 'Clôturer un mois avec un reste positif',
    rarity: 'commun',
    icon: 'Leaf',
    tone: 'mint',
    xp: 120,
  },
  {
    id: 'phoenix',
    label: 'Phénix',
    description: 'Repasser dans le vert après un mois à découvert.',
    criteria: 'Un mois positif juste après un mois négatif',
    rarity: 'rare',
    icon: 'Bird',
    tone: 'berry',
    xp: 400,
  },
  {
    id: 'no_atm_3',
    label: 'Sans distributeur',
    description: 'Trois mois de suite sans le moindre retrait d’espèces.',
    criteria: '3 mois consécutifs sans retrait',
    rarity: 'rare',
    icon: 'Landmark',
    tone: 'indigo',
    xp: 450,
  },
  {
    id: 'sub_slayer',
    label: 'Élagueur',
    description: 'Trois abonnements résiliés. Autant de charges fixes en moins, chaque mois.',
    criteria: 'Résilier 3 abonnements',
    rarity: 'rare',
    icon: 'Scissors',
    tone: 'orchid',
    xp: 380,
  },
  {
    id: 'saver_10',
    label: 'Dixième tenu',
    description: 'Trois mois consécutifs à plus de 10 % d’épargne.',
    criteria: '3 mois à 10 % d’épargne',
    rarity: 'rare',
    icon: 'PiggyBank',
    tone: 'amber',
    xp: 500,
  },
  {
    id: 'saver_20',
    label: 'Cinquième tenu',
    description: 'Six mois consécutifs à plus de 20 % d’épargne.',
    criteria: '6 mois à 20 % d’épargne',
    rarity: 'épique',
    icon: 'Gem',
    tone: 'amber',
    xp: 1200,
  },
  {
    id: 'emergency_1m',
    label: 'Premier matelas',
    description: 'Un mois de charges couvert par le fonds d’urgence.',
    criteria: "1 mois de charges en fonds d'urgence",
    rarity: 'rare',
    icon: 'Umbrella',
    tone: 'mint',
    xp: 600,
  },
  {
    id: 'emergency_3m',
    label: 'Trois mois devant',
    description: 'Trois mois de charges couverts. Le seuil qui change la vie.',
    criteria: "3 mois de charges en fonds d'urgence",
    rarity: 'épique',
    icon: 'ShieldCheck',
    tone: 'mint',
    xp: 1500,
  },
  {
    id: 'emergency_6m',
    label: 'Six mois de sérénité',
    description: 'Six mois de charges de côté. Vous pouvez voir venir.',
    criteria: "6 mois de charges en fonds d'urgence",
    rarity: 'légendaire',
    icon: 'Mountain',
    tone: 'mint',
    xp: 3000,
  },
  {
    id: 'debt_zero',
    label: 'Table rase',
    description: 'Plus une seule dette en cours.',
    criteria: 'Solder toutes les dettes',
    rarity: 'légendaire',
    icon: 'Sparkles',
    tone: 'amber',
    xp: 2500,
  },
  {
    id: 'goal_first',
    label: 'Objectif atteint',
    description: 'Votre premier objectif mené jusqu’au bout.',
    criteria: 'Atteindre un objectif',
    rarity: 'rare',
    icon: 'Flag',
    tone: 'orchid',
    xp: 700,
  },
  {
    id: 'goal_5',
    label: 'Collectionneur de sommets',
    description: 'Cinq objectifs atteints. Vous savez viser et finir.',
    criteria: 'Atteindre 5 objectifs',
    rarity: 'épique',
    icon: 'Trophy',
    tone: 'amber',
    xp: 2000,
  },
  {
    id: 'month_12',
    label: 'Année complète',
    description: 'Douze mois clôturés. Vous avez une vraie photo de votre année.',
    criteria: 'Clôturer 12 mois',
    rarity: 'épique',
    icon: 'CalendarRange',
    tone: 'indigo',
    xp: 1400,
  },
  {
    id: 'frugal_week',
    label: 'Semaine légère',
    description: 'Une semaine entière sans livraison de repas.',
    criteria: 'Réussir « Semaine sans livraison »',
    rarity: 'commun',
    icon: 'ChefHat',
    tone: 'mint',
    xp: 150,
  },
]

export const BADGE_BY_ID: Record<string, Badge> = Object.fromEntries(BADGES.map((b) => [b.id, b]))
